import { createApp } from 'vue'
import App from './App.vue'

import {
  // element-plus components
  ElAffix,
  ElAlert,
  ElAutocomplete,
  // ElAvatar,
  ElBacktop,
  ElBadge,
  // ElBreadcrumb,
  // ElBreadcrumbItem,
  ElButton,
  ElButtonGroup,
  // ElCalendar,
  ElCard,
  // ElCarousel,
  // ElCarouselItem,
  ElCascader,
  ElCascaderPanel,
  ElCheckTag,
  ElCheckbox,
  ElCheckboxButton,
  ElCheckboxGroup,
  ElCol,
  ElCollapse,
  ElCollapseItem,
  ElCollapseTransition,
  // ElColorPicker,
  ElConfigProvider,
  // ElContainer,
  // ElAside,
  // ElFooter,
  // ElHeader,
  // ElMain,
  ElDatePicker,
  ElDescriptions,
  ElDescriptionsItem,
  ElDialog,
  ElDivider,
  ElDrawer,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  ElEmpty,
  ElForm,
  ElFormItem,
  ElIcon,
  ElImage,
  ElImageViewer,
  ElInput,
  ElInputNumber,
  ElLink,
  ElMenu,
  ElMenuItem,
  ElSubMenu,
  ElMenuItemGroup,
  // ElPageHeader,
  ElPagination,
  ElPopconfirm,
  ElPopover,
  ElPopper,
  // ElProgress,
  ElRadio,
  ElRadioButton,
  ElRadioGroup,
  // ElRate,
  // ElResult,
  ElRow,
  ElScrollbar,
  ElSelect,
  ElOption,
  ElOptionGroup,
  ElSelectV2,
  ElSkeleton,
  ElSkeletonItem,
  // ElSlider,
  // ElSpace,
  // ElSteps,
  // ElStep,
  ElSwitch,
  ElTable,
  ElTableColumn,
  ElTabs,
  ElTabPane,
  ElTag,
  ElTimePicker,
  ElTimeSelect,
  // ElTimeline,
  // ElTimelineItem,
  ElTooltip,
  // ElTransfer,
  ElTree,
  ElTreeV2,
  ElUpload,
  ElMessage,
  ElMessageBox,
  ElNotification,
  // Directives
  ElInfiniteScroll,
  ElLoading,
} from 'element-plus'

// Directives
const elementPlusComponents = [
  ElAffix,
  ElAlert,
  ElAutocomplete,
  // ElAvatar,
  ElBacktop,
  ElBadge,
  // ElBreadcrumb,
  // ElBreadcrumbItem,
  ElButtonGroup,
  // ElCalendar,
  ElCard,
  // ElCarousel,
  // ElCarouselItem,
  ElCascader,
  ElCascaderPanel,
  ElCheckTag,
  ElCheckbox,
  ElCheckboxButton,
  ElCheckboxGroup,
  ElCol,
  ElCollapse,
  ElCollapseItem,
  ElCollapseTransition,
  // ElColorPicker,
  ElConfigProvider,
  // ElContainer,
  // ElAside,
  // ElFooter,
  // ElHeader,
  // ElMain,
  ElDatePicker,
  ElDescriptions,
  ElDescriptionsItem,
  ElDialog,
  ElDivider,
  ElDrawer,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  ElEmpty,
  ElForm,
  ElFormItem,
  ElIcon,
  ElImage,
  ElImageViewer,
  ElInput,
  ElInputNumber,
  ElLink,
  ElMenu,
  ElMenuItem,
  ElSubMenu,
  ElMenuItemGroup,
  // ElPageHeader,
  ElPagination,
  ElPopconfirm,
  ElPopover,
  ElPopper,
  // ElProgress,
  ElRadio,
  ElRadioButton,
  ElRadioGroup,
  // ElRate,
  // ElResult,
  ElRow,
  ElScrollbar,
  ElSelect,
  ElOption,
  ElOptionGroup,
  ElSelectV2,
  ElSkeleton,
  ElSkeletonItem,
  // ElSlider,
  // ElSpace,
  // ElSteps,
  // ElStep,
  ElSwitch,
  ElTable,
  ElTableColumn,
  ElTabs,
  ElTabPane,
  ElTag,
  ElTimePicker,
  ElTimeSelect,
  // ElTimeline,
  // ElTimelineItem,
  ElTooltip,
  // ElTransfer,
  ElTree,
  ElTreeV2,
  ElUpload,
  ElMessage,
  ElMessageBox,
  ElNotification,
  // element-plus directives
  ElInfiniteScroll,
  ElLoading,
]


const app = createApp(App)

elementPlusComponents.forEach((comp) => {
  app.use(comp)
})

app.mount('#app')
